#!/usr/bin/env python3
"""Post-hoc episode concentration diagnostics for Issue #64 Phase B.

This diagnostic does not alter the preregistered Reflation strategy. It asks
whether timing attribution versus an era realized-exposure-matched control is
broadly distributed or concentrated in a few Reflation episodes.

Leave-one-episode-out results are generated by disabling the selected Reflation
override episode and rerunning the portfolio from the beginning. This removes
both the episode's in-regime exposure and the associated entry/exit rebalance
path, rather than subtracting only status-True return rows.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from asset_allocation_phase_a import ASSETS
from asset_allocation_phase_b import (
    load_contract,
    month_start_mask,
    portfolio_metrics,
    segment_sim,
    simulate_portfolio,
    template_change_mask,
    weights_series,
)
from asset_allocation_phase_b_diagnostics import (
    build_realized_exposure_matched_controls,
    lagged_reflation_status,
    reconstruct_asset_returns,
)

DEVELOPMENT_END = pd.Timestamp("2019-12-31")
POST_START = pd.Timestamp("2020-01-01")


def contiguous_true_runs(mask: np.ndarray) -> list[tuple[int, int]]:
    runs: list[tuple[int, int]] = []
    start: int | None = None
    for i, value in enumerate(mask.astype(bool)):
        if value and start is None:
            start = i
        if start is not None and ((not value) or i == len(mask) - 1):
            end = i if value and i == len(mask) - 1 else i - 1
            runs.append((start, end))
            start = None
    return runs


def reflation_episode_table(status: pd.Series, active_log: pd.Series) -> pd.DataFrame:
    """Summarize contiguous Reflation episodes, including the exit row when present."""
    if not status.index.equals(active_log.index):
        raise ValueError("status and active_log must share one index")
    if status.empty:
        return pd.DataFrame(
            columns=[
                "start",
                "end",
                "days",
                "active_log_return_status_days",
                "active_log_return",
                "exit_day_included",
            ]
        )

    rows: list[dict] = []
    mask = status.astype(bool).to_numpy()
    for start, end in contiguous_true_runs(mask):
        contribution_end = min(end + 1, len(status) - 1)
        status_only = float(active_log.iloc[start : end + 1].sum())
        including_exit = float(active_log.iloc[start : contribution_end + 1].sum())
        rows.append(
            {
                "start": status.index[start],
                "end": status.index[end],
                "days": int(end - start + 1),
                "active_log_return_status_days": status_only,
                "active_log_return": including_exit,
                "exit_day_included": bool(contribution_end > end),
            }
        )
    return pd.DataFrame(rows)


def concentration_summary(
    label: str,
    status: pd.Series,
    active_log: pd.Series,
) -> tuple[dict, pd.DataFrame]:
    episodes = reflation_episode_table(status, active_log)
    total = float(active_log.sum())
    reflation_total = float(active_log.loc[status.astype(bool)].sum())
    non_reflation_total = float(active_log.loc[~status.astype(bool)].sum())
    positive = episodes.loc[episodes["active_log_return"] > 0.0].sort_values(
        "active_log_return", ascending=False
    )
    positive_sum = float(positive["active_log_return"].sum()) if not positive.empty else 0.0
    largest = float(positive.iloc[0]["active_log_return"]) if not positive.empty else 0.0

    def share(k: int) -> float:
        if positive_sum <= 0.0:
            return np.nan
        return float(positive.head(k)["active_log_return"].sum() / positive_sum)

    largest_row = positive.iloc[0] if not positive.empty else None
    summary = {
        "segment": label,
        "total_active_log_return": total,
        "reflation_day_active_log_return": reflation_total,
        "non_reflation_day_active_log_return": non_reflation_total,
        "reflation_episodes": int(len(episodes)),
        "positive_reflation_episodes": int(len(positive)),
        "positive_episode_fraction": float(len(positive) / len(episodes)) if len(episodes) else np.nan,
        "sum_positive_reflation_episode_active_log": positive_sum,
        "largest_positive_episode_active_log_including_exit_day": largest,
        "largest_positive_episode_start": (
            largest_row["start"].date().isoformat() if largest_row is not None else None
        ),
        "largest_positive_episode_end": (
            largest_row["end"].date().isoformat() if largest_row is not None else None
        ),
        "largest_positive_episode_days": int(largest_row["days"]) if largest_row is not None else 0,
        "top1_share_of_positive_episode_contribution": share(1),
        "top3_share_of_positive_episode_contribution": share(3),
        "top5_share_of_positive_episode_contribution": share(5),
    }
    episodes = episodes.copy()
    episodes.insert(0, "segment", label)
    return summary, episodes


def select_largest_positive_reflation_episode(
    status: pd.Series,
    active_log: pd.Series,
    *,
    segment_start: pd.Timestamp | None,
    segment_end: pd.Timestamp | None,
) -> dict:
    """Select a whole Reflation episode using contribution including its exit row."""
    if not status.index.equals(active_log.index):
        raise ValueError("status and active_log must share one index")
    index = status.index
    rows: list[dict] = []
    for start, end in contiguous_true_runs(status.astype(bool).to_numpy()):
        start_date = index[start]
        end_date = index[end]
        if segment_start is not None and start_date < segment_start:
            continue
        if segment_end is not None and end_date > segment_end:
            continue
        contribution_end = end
        if end + 1 < len(index):
            exit_date = index[end + 1]
            if segment_end is None or exit_date <= segment_end:
                contribution_end = end + 1
        contribution = float(active_log.iloc[start : contribution_end + 1].sum())
        if contribution <= 0.0:
            continue
        rows.append(
            {
                "start_position": start,
                "end_position": end,
                "start": start_date,
                "end": end_date,
                "screening_active_log_contribution_including_exit_day": contribution,
                "screening_exit_day_included": bool(contribution_end > end),
            }
        )
    if not rows:
        raise RuntimeError("no positive Reflation episode in requested segment")
    return max(rows, key=lambda row: row["screening_active_log_contribution_including_exit_day"])


def simulate_reflation_path(
    returns: pd.DataFrame,
    status: pd.Series,
    *,
    neutral_weights: dict[str, float],
    reflation_weights: dict[str, float],
    cost_bps: float,
    name: str,
) -> pd.DataFrame:
    """Replay a neutral/Reflation strategy from an already-lagged status series."""
    if not returns.index.equals(status.index):
        raise ValueError("returns and status must share one index")
    targets = weights_series(neutral_weights, returns.index)
    override = np.asarray([float(reflation_weights[a]) for a in ASSETS], dtype=float)
    targets.loc[status.astype(bool), list(ASSETS)] = override
    template = pd.Series(
        np.where(status.astype(bool).to_numpy(), "reflation", "neutral"),
        index=returns.index,
        dtype="object",
    )
    rebalance = (month_start_mask(returns.index) | template_change_mask(template)).astype(bool)
    return simulate_portfolio(
        returns,
        targets,
        rebalance,
        cost_bps=cost_bps,
        name=name,
    )


def metric_delta(lhs: dict, rhs: dict) -> dict:
    return {
        "delta_CAGR": float(lhs["CAGR"] - rhs["CAGR"]),
        "delta_Sharpe": float(lhs["Sharpe"] - rhs["Sharpe"]),
        "delta_maximum_drawdown": float(lhs["maximum_drawdown"] - rhs["maximum_drawdown"]),
        "delta_Calmar": float(lhs["Calmar"] - rhs["Calmar"]),
    }


def run_diagnostics(phase_b_dir: Path) -> dict:
    daily = pd.read_csv(phase_b_dir / "phase-b-daily.csv", parse_dates=["date"])
    manifest = json.loads((phase_b_dir / "phase-b-manifest.json").read_text(encoding="utf-8"))
    contract = load_contract()
    returns, residual = reconstruct_asset_returns(daily)
    if residual > 1e-10:
        raise AssertionError(f"asset-return reconstruction residual too large: {residual}")

    index = returns.index
    status = lagged_reflation_status(index)
    _, control, match_meta = build_realized_exposure_matched_controls(
        daily,
        returns,
        cost_bps=float(manifest["primary_cost_bps"]),
    )
    strategy = (
        daily.loc[daily["strategy"].eq("v66_reflation_override")]
        .set_index("date")
        .sort_index()
    )
    if not strategy.index.equals(control.index):
        raise AssertionError("strategy and exposure-matched control indices differ")

    rule = contract["strategy_rule"]
    neutral = contract["templates"][rule["default_template"]]
    reflation = contract["templates"][rule["override_template"]]
    cost_bps = float(manifest["primary_cost_bps"])
    replay = simulate_reflation_path(
        returns,
        status,
        neutral_weights=neutral,
        reflation_weights=reflation,
        cost_bps=cost_bps,
        name="phase_b_reflation_replay",
    )
    replay_error = float(
        np.max(np.abs(replay["net_return"].to_numpy(float) - strategy["net_return"].to_numpy(float)))
    )
    if replay_error > 1e-12:
        raise AssertionError(f"Phase B replay error too large: {replay_error}")

    active_log = np.log1p(strategy["net_return"].astype(float)) - np.log1p(
        control["net_return"].astype(float)
    )

    segments = {
        "full_reused_history": (None, None),
        "development_pre2020": (None, DEVELOPMENT_END),
        "post2019_reused_exploratory": (POST_START, None),
    }
    summaries: list[dict] = []
    episode_frames: list[pd.DataFrame] = []
    for label, (start, end) in segments.items():
        mask = pd.Series(True, index=index)
        if start is not None:
            mask &= index >= start
        if end is not None:
            mask &= index <= end
        sub_status = status.loc[mask]
        sub_active = active_log.loc[mask]
        summary, episodes = concentration_summary(label, sub_status, sub_active)

        winner = select_largest_positive_reflation_episode(
            status,
            active_log,
            segment_start=start,
            segment_end=end,
        )
        modified_status = status.copy()
        s = int(winner["start_position"])
        e = int(winner["end_position"])
        modified_status.iloc[s : e + 1] = False
        leaveout = simulate_reflation_path(
            returns,
            modified_status,
            neutral_weights=neutral,
            reflation_weights=reflation,
            cost_bps=cost_bps,
            name=f"phase_b_leaveout_{label}",
        )

        start_str = None if start is None else start.date().isoformat()
        end_str = None if end is None else end.date().isoformat()
        strategy_seg = segment_sim(strategy, start_str, end_str)
        control_seg = segment_sim(control, start_str, end_str)
        leaveout_seg = segment_sim(leaveout, start_str, end_str)
        normal_active_log = float(
            np.log1p(strategy_seg["net_return"]).sum() - np.log1p(control_seg["net_return"]).sum()
        )
        leaveout_active_log = float(
            np.log1p(leaveout_seg["net_return"]).sum() - np.log1p(control_seg["net_return"]).sum()
        )
        normal_metrics = metric_delta(
            portfolio_metrics(strategy_seg, annualization=252),
            portfolio_metrics(control_seg, annualization=252),
        )
        leaveout_metrics = metric_delta(
            portfolio_metrics(leaveout_seg, annualization=252),
            portfolio_metrics(control_seg, annualization=252),
        )

        summary.update(
            {
                "largest_positive_episode_start": winner["start"].date().isoformat(),
                "largest_positive_episode_end": winner["end"].date().isoformat(),
                "screening_active_log_contribution_including_exit_day": float(
                    winner["screening_active_log_contribution_including_exit_day"]
                ),
                "screening_exit_day_included": bool(winner["screening_exit_day_included"]),
                "normal_active_log_return": normal_active_log,
                "active_log_after_removing_largest_positive_reflation_episode": leaveout_active_log,
                "normal_incremental": normal_metrics,
                "incremental_after_leaveout": leaveout_metrics,
                "leaveout_method": "disable selected Reflation override episode and rerun full portfolio path",
            }
        )
        summaries.append(summary)
        if label != "full_reused_history":
            episode_frames.append(episodes)

    pd.DataFrame(summaries).to_csv(
        phase_b_dir / "phase-b-posthoc-timing-concentration-summary.csv", index=False
    )
    pd.concat(episode_frames, ignore_index=True).to_csv(
        phase_b_dir / "phase-b-posthoc-reflation-episodes.csv",
        index=False,
        date_format="%Y-%m-%d",
    )

    result = {
        "schema_version": 3,
        "issue": 64,
        "phase": "B-posthoc-timing-concentration",
        "preregistered_primary_result_modified": False,
        "purpose": "measure whether Reflation timing attribution is broad or dominated by a small number of episodes",
        "causal_investable_benchmark": False,
        "control": "posthoc era realized-exposure-matched allocation",
        "asset_return_reconstruction_max_abs_residual": residual,
        "phase_b_replay_max_abs_net_return_error": replay_error,
        "realized_exposure_matching": match_meta,
        "summary_rows": summaries,
        "leaveout_semantics": "selected whole Reflation override episode is disabled and the portfolio is rerun from inception, so entry/exit rebalance costs and subsequent drift are recomputed rather than retained",
        "interpretation_boundary": "Post-hoc attribution only. Episode concentration cannot upgrade reused-history evidence to confirmation and must not be used to retune the strategy.",
    }
    (phase_b_dir / "phase-b-posthoc-timing-concentration.json").write_text(
        json.dumps(result, indent=2, ensure_ascii=False, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Issue #64 Phase B episode concentration diagnostic")
    parser.add_argument("--phase-b-dir", type=Path, required=True)
    args = parser.parse_args()
    result = run_diagnostics(args.phase_b_dir)
    print(json.dumps({"summary_rows": result["summary_rows"]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
