#!/usr/bin/env python3
"""Issue #109 A2S current-Feed trajectory screening.

This evaluator is intentionally screening-only. It compares the frozen A1
state-only baseline (M0) with M0 plus six current-Feed trajectory features (M1).

Required external inputs:
- user/operator-local r4 Pine Logs file (hash-frozen in finding/prereg)
- A1 monthly origins CSV generated by issue_109_action_layer_a1.py

No production authorization is implied by this screen.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
from pathlib import Path

import numpy as np
import pandas as pd

FEATURES = [
    "gpi_fast20",
    "gpi_mid63",
    "gpi_acc",
    "ipi_fast20",
    "ipi_mid63",
    "ipi_acc",
]
EXPECTED_R4_SHA256 = "6ceb8cf7ba0e9c17949a4d8892b91f9a8c3a94ea1f7462a5b0a4ce114cf5e1bc"
PRIMARY_HORIZON = "3M"
MIN_TRAIN_ROWS = 84

PATTERN = re.compile(
    r"MPM_A2"
    r"\|date=(?P<date>\d{4}-\d{1,2}-\d{1,2})"
    r"\|raw_gpi=(?P<raw_gpi>[^|\s]+)"
    r"\|raw_ipi=(?P<raw_ipi>[^|\s]+)"
    r"\|gpi_fast20=(?P<gpi_fast20>[^|\s]+)"
    r"\|gpi_mid63=(?P<gpi_mid63>[^|\s]+)"
    r"\|gpi_acc=(?P<gpi_acc>[^|\s]+)"
    r"\|ipi_fast20=(?P<ipi_fast20>[^|\s]+)"
    r"\|ipi_mid63=(?P<ipi_mid63>[^|\s]+)"
    r"\|ipi_acc=(?P<ipi_acc>[^|\s]+)"
    r"\|regime_id=(?P<regime_id>[^|\s]+)"
    r"\|helper_rev=(?P<helper_rev>[^|\s]+)"
)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def parse_r4(path: Path) -> pd.DataFrame:
    if sha256_file(path) != EXPECTED_R4_SHA256:
        raise ValueError("r4 Pine Logs SHA-256 mismatch")

    raw = pd.read_csv(path)
    if "訊息" not in raw.columns:
        raise ValueError("Pine Logs CSV is missing 訊息 column")

    rows: dict[str, dict[str, str]] = {}
    revisions: list[str] = []
    for message in raw["訊息"].astype(str):
        m = PATTERN.search(message)
        if not m:
            continue
        row = m.groupdict()
        revisions.append(row["helper_rev"])
        rows[row["date"]] = row

    if not rows:
        raise ValueError("no MPM_A2 r4 payloads found")
    if set(revisions) != {"r4sc"}:
        raise ValueError(f"unexpected helper revisions: {sorted(set(revisions))}")

    df = pd.DataFrame([rows[k] for k in sorted(rows)])
    df["date"] = pd.to_datetime(df["date"], errors="raise")
    for col in ["raw_gpi", "raw_ipi", *FEATURES, "regime_id"]:
        df[col] = pd.to_numeric(df[col], errors="raise").astype(float)
    return df.sort_values("date").reset_index(drop=True)


def state_design(regime_ids: np.ndarray) -> np.ndarray:
    reg = np.asarray(regime_ids, dtype=int)
    dummies = [(reg == k).astype(float) for k in range(2, 10)]
    return np.column_stack([np.ones(len(reg)), *dummies])


def fit_predict(train: pd.DataFrame, row: pd.Series, use_trajectory: bool) -> float:
    x0_train = state_design(train["regime_id"].to_numpy(int))
    x0_row = state_design(np.array([int(row["regime_id"])]))

    if not use_trajectory:
        x_train = x0_train
        x_row = x0_row
    else:
        mean = train[FEATURES].mean(axis=0).to_numpy(float)
        std = train[FEATURES].std(axis=0, ddof=0).to_numpy(float)
        if np.any(~np.isfinite(std)) or np.any(std <= 1e-12):
            return math.nan
        z_train = (train[FEATURES].to_numpy(float) - mean) / std
        z_row = (row[FEATURES].to_numpy(float) - mean) / std
        x_train = np.column_stack([x0_train, z_train])
        x_row = np.column_stack([x0_row, z_row.reshape(1, -1)])

    y = train["pairwise_spread"].to_numpy(float)
    beta = np.linalg.lstsq(x_train, y, rcond=None)[0]
    return float((x_row @ beta).item())


def metrics(frame: pd.DataFrame, pred_col: str) -> dict:
    y = frame["pairwise_spread"].to_numpy(float)
    p = frame[pred_col].to_numpy(float)
    mask = np.isfinite(y) & np.isfinite(p)
    y = y[mask]
    p = p[mask]
    if len(y) == 0:
        return {"n": 0}

    corr = (
        float(np.corrcoef(p, y)[0, 1])
        if len(y) >= 2 and np.std(p) > 0 and np.std(y) > 0
        else math.nan
    )
    return {
        "n": int(len(y)),
        "rmse": float(np.sqrt(np.mean((p - y) ** 2))),
        "mae": float(np.mean(np.abs(p - y))),
        "corr": corr,
        "sign_agreement": float(np.mean(np.sign(p) == np.sign(y))),
        "realized_mean_pred_positive": float(np.mean(y[p > 0])) if np.any(p > 0) else math.nan,
        "realized_mean_pred_negative": float(np.mean(y[p < 0])) if np.any(p < 0) else math.nan,
    }


def evaluate_leg(frame: pd.DataFrame) -> pd.DataFrame:
    g = frame.sort_values("origin_date").reset_index(drop=True)
    rows: list[dict] = []

    for i, row in g.iterrows():
        # Outcome availability gate: a prior row enters training only after its
        # 3M end date is strictly before this forecast origin.
        train = g.loc[(g.index < i) & (g["end_date"] < row["origin_date"])].copy()
        if len(train) < MIN_TRAIN_ROWS:
            continue

        rows.append(
            {
                "leg": row["leg"],
                "origin_date": row["origin_date"],
                "end_date": row["end_date"],
                "segment": row["segment"],
                "regime_id": int(row["regime_id"]),
                "regime": row["regime"],
                "pairwise_spread": float(row["pairwise_spread"]),
                "pred_m0": fit_predict(train, row, False),
                "pred_m1": fit_predict(train, row, True),
                "train_n": int(len(train)),
            }
        )

    return pd.DataFrame(rows)


def screen_verdict(full_m0: dict, full_m1: dict, segments: list[dict]) -> str:
    # A positive screen requires full-sample error improvement plus non-worse
    # correlation/sign behavior and consistent support across >=2 usable eras.
    error_improved = (
        full_m1["rmse"] < full_m0["rmse"] or full_m1["mae"] < full_m0["mae"]
    )
    corr_preserved = full_m1["corr"] >= full_m0["corr"]
    sign_not_materially_worse = (
        full_m1["sign_agreement"] >= full_m0["sign_agreement"] - 0.02
    )

    supportive_eras = 0
    usable_eras = 0
    for item in segments:
        m0, m1 = item["m0"], item["m1"]
        if m0.get("n", 0) < 5:
            continue
        usable_eras += 1
        era_error = m1["rmse"] < m0["rmse"] or m1["mae"] < m0["mae"]
        era_corr = m1["corr"] >= m0["corr"]
        era_sign = m1["sign_agreement"] >= m0["sign_agreement"] - 0.02
        if era_error and era_corr and era_sign:
            supportive_eras += 1

    if usable_eras < 2:
        return "trajectory_screen_inconclusive"
    if error_improved and corr_preserved and sign_not_materially_worse and supportive_eras >= 2:
        return "trajectory_screen_positive"
    return "trajectory_screen_negative"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pine-log", type=Path, required=True)
    ap.add_argument("--a1-origins", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, required=True)
    args = ap.parse_args()

    r4 = parse_r4(args.pine_log)
    a1 = pd.read_csv(args.a1_origins)
    a1 = a1.loc[a1["horizon"].eq(PRIMARY_HORIZON)].copy()
    for col in ("origin_date", "signal_date", "end_date"):
        a1[col] = pd.to_datetime(a1[col], errors="raise")

    merged = a1.merge(
        r4[["date", *FEATURES]],
        left_on="signal_date",
        right_on="date",
        how="left",
        validate="many_to_one",
    )
    if merged[FEATURES].isna().any(axis=None):
        missing = int(merged[FEATURES].isna().any(axis=1).sum())
        raise ValueError(f"missing trajectory features on {missing} A1 signal dates")

    predictions = pd.concat(
        [evaluate_leg(g) for _, g in merged.groupby("leg", sort=True)],
        ignore_index=True,
    )

    metric_rows: list[dict] = []
    verdicts: dict[str, str] = {}
    for leg, g in predictions.groupby("leg", sort=True):
        scope_frames = [("full", g)]
        for scope in ("pre_2020", "covid_inflation_2020_2022", "post_2023"):
            scope_frames.append((scope, g.loc[g["segment"].eq(scope)]))

        segment_items = []
        for scope, sg in scope_frames:
            m0 = metrics(sg, "pred_m0")
            m1 = metrics(sg, "pred_m1")
            metric_rows.append(
                {
                    "leg": leg,
                    "scope": scope,
                    "m0": m0,
                    "m1": m1,
                    "delta_m1_minus_m0": {
                        key: (
                            float(m1[key] - m0[key])
                            if key in m0 and key in m1 and isinstance(m0[key], (int, float))
                            else None
                        )
                        for key in ("rmse", "mae", "corr", "sign_agreement")
                    },
                }
            )
            if scope != "full":
                segment_items.append({"scope": scope, "m0": m0, "m1": m1})

        full = [x for x in metric_rows if x["leg"] == leg and x["scope"] == "full"][0]
        verdicts[leg] = screen_verdict(full["m0"], full["m1"], segment_items)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    pred_path = args.output_dir / "issue-109-a2s-predictions.csv"
    predictions.to_csv(pred_path, index=False, float_format="%.12g")

    result = {
        "schema_version": 1,
        "issue": 109,
        "phase": "A2S-current-feed-trajectory-screen",
        "source_r4_sha256": EXPECTED_R4_SHA256,
        "source_r4_rows_unique": int(len(r4)),
        "source_r4_first_date": r4["date"].min().date().isoformat(),
        "source_r4_last_date": r4["date"].max().date().isoformat(),
        "primary_horizon": PRIMARY_HORIZON,
        "min_training_rows": MIN_TRAIN_ROWS,
        "features": FEATURES,
        "metrics": metric_rows,
        "verdicts": verdicts,
        "production_authorized": False,
        "exact_v66_trajectory_validated": False,
        "predictions_sha256": sha256_file(pred_path),
    }
    out = args.output_dir / "issue-109-a2s-result.json"
    out.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"verdicts": verdicts, "output": str(out)}, indent=2))


if __name__ == "__main__":
    main()
