#!/usr/bin/env python3
"""Print the Python/Yahoo decision chain for the 2024-04-16 Issue #55 divergence.

This is diagnostic only. It intentionally does not alter model parameters or
claim parity. The output is designed to line up one-for-one with the focused
TradingView/OANDA deep diagnostic table generated by
``generate_2024_deep_diagnostic_pine.py``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from compare_reference_feed import DEFAULT_TICKER, download_yahoo, normalize_ohlc
from price_only_core import compute_price_only


TARGET = "2024-04-16"
DISPLAY_FIELDS = [
    "speed_rank",
    "accel_rank",
    "dist_rank",
    "heat_up",
    "panic_heat_dn",
    "maturity_up",
    "maturity_dn",
    "range_score",
    "upside_exhaustion",
    "resistance_holding",
    "dist_raw",
    "dist_gate",
    "dist_eff",
    "prob_dist",
    "top_gap",
    "evidence_strength",
    "downside_exhaustion",
    "support_holding",
    "markdown_extension_score",
    "markdown_continuation_score",
    "markdown_raw",
    "markdown_gate",
    "markdown_eff",
    "prob_markdown",
]


def _number(value, *, percent_gate: bool = False):
    value = float(value)
    if not np.isfinite(value):
        return None
    if percent_gate:
        value *= 100.0
    return value


def build_report(ticker: str, reference_path: Path) -> dict:
    reference = json.loads(reference_path.read_text(encoding="utf-8"))
    _, downloaded = download_yahoo(ticker)
    ohlc = normalize_ohlc(downloaded)
    result = compute_price_only(ohlc)

    target = pd.Timestamp(TARGET).date()
    matches = result.index[result["date"] >= target].tolist()
    if not matches:
        raise ValueError(f"no Yahoo bar at or after {TARGET}")
    idx = matches[0]
    row = result.loc[idx]

    tv_ref = next(item for item in reference["rows"] if item["target_date"] == TARGET)
    values = {}
    for field in DISPLAY_FIELDS:
        values[field] = _number(row[field], percent_gate=field in {"dist_gate", "markdown_gate"})

    neighbor_fields = [
        "date",
        "close",
        "prob_dist",
        "prob_markdown",
        "dist_gate",
        "markdown_gate",
        "dist_eff",
        "markdown_eff",
        "candidate_display_id",
        "formal_id",
    ]
    start = max(0, idx - 3)
    stop = min(len(result), idx + 4)
    neighbors = []
    for _, neighbor in result.loc[start : stop - 1, neighbor_fields].iterrows():
        neighbors.append(
            {
                "date": str(neighbor["date"]),
                "close": _number(neighbor["close"]),
                "prob_dist": _number(neighbor["prob_dist"]),
                "prob_markdown": _number(neighbor["prob_markdown"]),
                "dist_gate_pct": _number(neighbor["dist_gate"], percent_gate=True),
                "markdown_gate_pct": _number(neighbor["markdown_gate"], percent_gate=True),
                "dist_eff": _number(neighbor["dist_eff"]),
                "markdown_eff": _number(neighbor["markdown_eff"]),
                "candidate": int(neighbor["candidate_display_id"]),
                "formal": int(neighbor["formal_id"]),
            }
        )

    return {
        "status": "diagnostic_cross_feed_only",
        "target_date": TARGET,
        "public_feed": "Yahoo Finance via yfinance",
        "ticker": ticker,
        "public_bar_date": str(row["date"]),
        "public_close": _number(row["close"]),
        "tradingview_oanda_reference": {
            "actual_bar_date": tv_ref["actual_bar_date"],
            "close": tv_ref["close"],
            "prob_dist": tv_ref["prob_dist"],
            "prob_markdown": tv_ref["prob_markdown"],
            "top_gap": tv_ref["top_gap"],
            "evidence_strength": tv_ref["evidence_strength"],
            "candidate": tv_ref["candidate_display_id"],
            "formal": tv_ref["formal_id"],
        },
        "python_yahoo_intermediate_values": values,
        "neighbor_window": neighbors,
        "boundary": "The TradingView deep table must be compared before deciding whether the first divergence is feed sensitivity or a Pine/Python semantic mismatch. No parameter changes are allowed from this diagnostic.",
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    here = Path(__file__).resolve().parent
    parser.add_argument("--ticker", default=DEFAULT_TICKER)
    parser.add_argument(
        "--reference",
        type=Path,
        default=here / "fixtures" / "issue-55-oanda-eurusd-tv-checkpoints-v1.json",
    )
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    report = build_report(args.ticker, args.reference)
    text = json.dumps(report, indent=2, ensure_ascii=False) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
    print(text, end="")


if __name__ == "__main__":
    main()
